### ISSUE TITLE
Implement OCL Online user Groups & Roles

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#127]
Time to implement actual User Groups and Roles in OCL Online, while maintaining compatibility with Django-auth or simple Key Cloak implementations for those who self-deploy.

Default user groups for all deployments of OCL -- these are implemented out of the box for django-auth and for basic keycloak implementations:
- `Guest` - anonymous access
- `Standard` - standard authenticated access

For OCL Online, the following groups will be implemented in KeyCloak:
- `Guest` - anonymous access
- `Standard` - this what we refer to as the "community" tier with free basic access to OCL Online, and possibly trial access to premium features
- `Early Access` - this is our temporary early access group with some trial access to premium features; we will create a few more early access groups to help us manage different tiers of use
- `Premium` - a paid account with access to premium features
- `Staff` - access to most functionality in OCL (Joe, Jon, Sunny, etc.)
- `superadmin` - access to all functionality in OCL; this is not intended to be used even by `Staff` users except when something goes wrong

Acceptance criteria:
- [x] Basic groups/permissions implemented in default django-auth and keycloak configurations and work as expected in the TermBrowser
- [x] OCL Online groups implemented and available in OCL Online KeyCloak
- [x] For the initial rollout, assignment of OCL Online account types happens directly in KeyCloak; new users default to Standard
- [x] The OCL Online deployment of TermBrowser v3 should check permissions against this new setup
- [ ] Self-deployed versions of TBv3 and TBv2 must continue to work with existing set ups
- [ ] Implement roles and permissions for OCL Online, assign to groups, and activate

**Comment by paynejd** [comment]
First round of group/roles/permissions for OCL Online

**Groups:**
- Guest → `guest_user`
- Standard User → `standard_user`
- Premium User → `premium_user`
- Core Group → `core_user`
- Staff User → `staff_user`
- Superadmin → `superadmin_user`

**Roles:**
- Mapper Standard User → `mapper_standard_user`
- Mapper Premium User → `mapper_premium_user`
- Mapper Core User → `mapper_core_user`
- TermBrowser Core Contributor → TBD

**Permissions:**
_Start with just the permissions that only the core group has_
- Multi-algo config
- AI Assistant:
  - Recommendation
  - Model Selection
  - Prompt template selection
- Change lookup configuration
- Reranker selection
- Match in TBv3 search light

**Comment by paynejd** [comment]
MVP: Switch premium features over to the Core_users group
