### ISSUE TITLE
[SSO] KeyCloak Setup and Implementation

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1338]
#### Tasks (High Level)
- [x] Setup Keycloak docker container
- [x] Configure Keycloak (manual) -- realm,client,roles
- [x] Use [django-keycloak-auth](https://github.com/marcelo225/django-keycloak-auth) or some generic  django+openid-connector package.
- [x] Integrate OCL API with KeyCloak using above package (or custom) and using openid-connect (not SAML)
- [x] Plugin authenticate process to get user token
- [x] Plugin Signup Process.

Questions:
- Whats the password encryption scheme of KeyCloak? Can the password be migrated from django to KeyCloak?

Other Notes:
- TermBrowser may need to talk to KeyCloak for initiating signup process via keyCloak
- Django should always ask keycloak if user’s authenticated or not

**Comment by paynejd** [comment]
Migration to KeyCloak will change the API tokens for all users

**Comment by snyaggarwal** [comment]
Task Steps:

- KeyCloak Setup:
  - Docker container (part of ocl-api-core docker-compose.yml)
  - (manual) [Create/Configure](https://www.keycloak.org/docs/latest/server_admin/#configuring-realms) realm _OCL_
  - Create Client (per env) in OCL realm with base URL (ocl-qa with base URL https://api.qa.agrichain.com)
  - Set client's Access Type as confidential and copy client-id/secret from Credentials
  - Add roles in client if any.
  - Create Users in OCL realm, set credentials and assign roles.
 
 - Configuring OCLAPI:
   - Update the following env vars:
     - OIDC_SERVER_URL
     - OIDC_SERVER_INTERNAL_URL (should be same as OIDC_SERVER_URL for non-dev)
     - OIDC_REALM
     - OIDC_RP_CLIENT_ID
     - OIDC_RP_CLIENT_SECRET

**Comment by snyaggarwal** [comment]
TODO:

- [ ] Signup (wip)
- [ ] Forgot/Reset password
- [ ] Token expiry handling on TermBrowser

**Comment by rkorytkowski** [comment]
@snyaggarwal I think we need to revisit the approach a bit and when switching to use oidc server we should really be redirecting users to Keycloak for login / logout / singup / forgot password.  We can then easily rely on Keyclock providing MFA, adding other identity providers like Google, Facebook, etc. We are also more secure as OCLAPI code is not storing or handling any user credentials and we are not responsible for any password leaks. See https://oauth.net/2/grant-types/password/ which explicitly says it is not recommended that this grant be used at all anymore.

**Comment by rkorytkowski** [comment]
https://www.keycloak.org/docs/latest/server_development/#_themes is how we would go about customizing the keycloak theme.

**Comment by snyaggarwal** [comment]
@rkorytkowski Alight! I am working on the setup.

**Comment by snyaggarwal** [comment]
https://docs.google.com/document/d/116PlRJv1-5qAIADkkaVnkxnjkwKBPWqQ95-wJ2KZLFw/edit

**Comment by rkorytkowski** [comment]
@snyaggarwal I did a further reading and there's a flow in OAuth that is targeted for API clients apps, scripts, etc. https://www.appsdeveloperblog.com/keycloak-client-credentials-grant-example/ It's basically a client with the "service accounts" enabled and other flows disabled. My understanding is that regular users cannot add clients so we would have to develop some code to create clients with OCLAPI2 authenticated as an admin to Keycloack via REST to do on behalf of regular users, if they need that or say that it needs be done manually by admins. Anyway for the POC we can stick with Django tokens we store in OCLAPI2 and maybe support OAuth client apps added by an admin.

**Comment by snyaggarwal** [comment]
Added KeyClock settings:
https://github.com/OpenConceptLab/oclsso/blob/main/README.md

**Comment by snyaggarwal** [comment]
[KeyCloak Integration Options](https://docs.google.com/document/d/116PlRJv1-5qAIADkkaVnkxnjkwKBPWqQ95-wJ2KZLFw/edit#):
Recommended:

**Option 3 - response_type=code with grant_type=authorization_code**
- More secure approach, because OCL never has access to passwords
- TermBrowser redirects to KeyCloak for Sign-in (with client_id and redirect_uri and response_type=code) without client_secret
- On success, KeyCloak will redirect to TermBrower with authorization_code in URL as a query param
- TermBrowser will make an API call to OCLAPI with that authorization_code and OCLAPI will make a REST call to OID to exchange it for Auth token (access_token) and return to TermBrowser

**Comment by snyaggarwal** [comment]
@paynejd @rkorytkowski following changes are done:
1. Logout is done in a similar way as login (without OCLAPI and without keycloak admin credentials).
2. After Login, from the user details screen can copy Django token.

**Comment by paynejd** [comment]
Key behaviors that need to be tested as deploy on the QA and staging environments:
- Sign up
- Sign in
- Sign out
- Forgot/Reset password
- Admin has a few more actions

**Comment by paynejd** [comment]
Next stesps:
- [ ] Merge into master, deploy to QA
- [ ] Test in QA
- [ ] Sunny to write document describing how a client should interact with KeyCloak, using Dictionary Manager as the example

**Comment by snyaggarwal** [comment]
@rkorytkowski Moving this to Code Review.

**Comment by snyaggarwal** [comment]
@paynejd @rkorytkowski A new Client integration [documentation](https://docs.google.com/document/d/1-NaFPHbG3OinuXOvzaXjCgLLGLCadXbn9bZjN63r57k/edit?usp=sharing)

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd @rkorytkowski This is now merged with master and deployed on QA (with SSO disabled)

**Comment by jamlung-ri** [comment]
@paynejd and @jamlung-ri to test this on Dev

**Comment by rkorytkowski** [comment]
We'll deploy it to production with #1405. The production deployment awaits #1389.

**Comment by paynejd** [comment]
Note that OID-compatible features for the API were merged into master and were deployed to all environments. KeyCloak is deployed for OCL Online and only a single instance will be used for all environments.

Currently, SSO has been enabled only on `dev`, and that included a migration of user accounts from `dev`.

Next steps include:
- Integrating OpenMRS Dictionary Manager with KeyCloak and testing
- Migrating user accounts and activating SSO in each environment + testing
- Identifying dependencies between the OCL Online rollout and upcoming support for the WHO-hosted Azure Active Directory deployment
