### ISSUE TITLE
Organize a meeting for OCL Roadmap discussion

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#159]
- [ ] compile already what we know already - #158 
- [ ] Setup a One on One calls #160
- [x] invite - Week of 6th October Mid morning Tuesday or Friday  or Wednesday work best - https://doodle.com/poll/iveuikvnh8psra9g
   - [x] Ellen Ball
   - [x] Carl Lietner 
   - [x] Andy Kanter 
   - [x] Darius
   - [x] Rafal
   - [x] Lincon karahunga
   - [x] Jennifer Antilla
   - [x] Cynthia
- [x] Finalize a Date
- [ ] Send the finalized date to  openhie list serv
- [ ] Invite and Schedule another followup meeting
- [ ] Create guidance on how to participate
- [ ] Provide guidance before meeting on how to participate
- [ ] Create a google doc/google spreadsheets to write/brainstorm ideas, 
- [ ] To participants who can't make the meeting provide guidance on how to participate before or after
