### ISSUE TITLE
Consumer: Repository

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1625]

**Comment by jamlung-ri** [comment]
@paulsonder I'm going to list out some details below for what information a user needs to see on a Repository, while trying to be generic with respect to the type of Repo.

* Basic required info:
     * Name plus ID for the repo
     * OCL type (dictionary, source, collection, etc.)
     * Owner (i.e. org or user)
* Secondary optional/helpful info (which would not be displayed primarily but should ideally be accessible and/or viewable):
     * Content summary: # of concepts and released versions
     * Date of last released version
     * Canonical URL
     * Permission level i.e. public for all, private, etc.
* Info specific to "Classic Source":
* Info specific to "Classic Collection":

**Comment by jamlung-ri** [comment]
In addition to the info above, here are the CTAs and User Stories relevant to Repositories:

Object +   CTA | User   Story | Requirements
-- | -- | --
Repository: View | View metadata and content list of a repository | About   page viewer; Empty state for a repository that has no About section; summary   statistics (see above); concept list with hierarchy, card, and table views;   mapping list with map type-, source-, and target-focused views; repo version   navigator
Repository: Search | Find a specific repo using full text search or parameter-based search (e.g. any   search param supported in FHIR spec or OCL API) | Support [FHIR Search Parameters](https://www.hl7.org/fhir/codesystem.html#search);   support sorting and filtering by OCL attributes; repo list with card and   table views
Repository: Compare | See   a comparison of two versions of a specified repository, including a summary   of differences (e.g. stats) and a list of specific changes (e.g. "New   concepts", "Retired concepts", etc. | Select two versions to compare,   which shows summary of differences between repos as outlined in #1753
Repository: Export | Download   an export of a repository in preferred format | OCL zip, csv, and JSON formats;   FHIR resource format(s) available, based on repo type (e.g. value set can be   downloaded as FHIR ValueSet, Classic Source can be downloaded as CodeSystem   or ConceptMap)
Repository: Bookmark / Star | Get   notifications on selected repositories, e.g. new releases, new versions   created. | Add repository to user's   Bookmarked Repos list
Repository: Operations | View   a list of possible operations and supported parameters and a way to trigger   the operation and see results | See #1624
Repository: Share | Share/copy   a link to a repo | Copy repo link to clipboard

**Comment by jamlung-ri** [comment]
@paulsonder Adding FHIR acceptance criteria for repository. Let's make sure these are covered somewhere. I'll put a suggested ticket next to each one - let me know if it helps to add each checklist item to the ticket itself.

- [ ] Header: View Repo's identity (incl. ID, canonical URL, version, name, title) (#1871)
- [ ] Metadata: View Repo attributes: publication status, experimental, date, publisher, contact, description, useContext, jurisdiction, purpose, copyright, caseSensitive, valueSet, hierarchyMeaning, compositional, versionNeeded, content, supplements, count (#1699)
- [ ] View Repo's Narrative: (Represented by the text element.) This allows a human to safely view a resource using a browser without having to parse the content in JSON or XML. (#1699)
- [ ] View extensions: Display attributes and extended resource content that fits outside of FHIR R4 and OCL data models (Need new ticket and requirements)
- [ ] View Core Content: CodeSystem filters, properties, concepts; ValueSet compose, expansion; ConceptMap source, target, groups (@paulsonder do you have a ticket where you are tracking the Concepts section of a repo?)

**Comment by paynejd** [comment]
Reviewed by Jonathan and Joe and determined to be completed for the TBv3 alpha launch. Closing.
