### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1854]
References are the “instructions” to tell OCL what resources to put in your collection and how to do it. References are akin to FHIR's logical definition, sometimes known as the Compose statement of a [ValueSet](https://www.hl7.org/fhir/valueset.html). 

In OCL, references often point to either concepts or mappings; they can also point to something broader e.g. all concepts in a repository. You can have one reference per concept that you want in your collection, or you can have one reference that brings in multiple concepts or mappings. Additionally, any reference can either be an INCLUDE or an EXCLUDE reference, which determines whether the concept(s)/mapping(s) should be brought into the collection or if they should be specifically omitted from the collection.

References also can have "Cascade" parameters, which tell OCL to not only get a single concept, but also to traverse the associations (i.e. mappings or hierarchy) of a concept to bring in more concepts. For example, users will often add an entire Concept Set to their collection, which brings in the concept for the set, plus any question concepts within that set, plus any answer concepts underneath those questions, and so on.

References can sometimes point to a specific version of a repository, but they often simply point to one or more concepts/mappings themselves without specifying a version. In this case, version resolution happens as part of building a collection expansion. Best practices for modeling references can be found in this document: https://docs.google.com/document/d/1QvWX0H6TP1_yJSiNkE9xWIrYmn9opp6O0-qQp57m4zc/edit

**Comment by jamlung-ri** [comment]
One note about this: our current model of reference building in the API is not entirely FHIR conformant. It may not necessarily be FHIR-illegal, but it at least doesn't go along with most of the value set building norms that FHIR would do. Several examples of this have come out of the Phase 2 Kenya SMART Guidelines project.

**Comment by jamlung-ri** [comment]
Basic mockup (see [reference tab mockup](https://github.com/OpenConceptLab/ocl-kb/blob/main/tbv3/04_surfaces/mockups/repository-page-references-mockup.html) for full HTML mockups):

<img width="1003" height="570" alt="Image" src="https://github.com/user-attachments/assets/8cf64d18-cd4e-4728-bcb0-2094f989cdaa" />

**Comment by jamlung-ri** [comment]
@snyaggarwal  This is ready for development!

To Do:

- [x] Include Reference Translations with optional "raw" reference toggle
- [x] Enhance table rows with tags for reference type, resolved repo, and result counts
- [ ] Add Expansion dropdown to select other expansions (which will update the Resolved Repo and Results)

**Comment by snyaggarwal** [comment]
@jamlung-ri A PR is raised for most of the changes except expansion.
Can you please describe workflow for expansion here.

**Comment by jamlung-ri** [comment]
Awesome! Most things are working well — below are the issues I found:

### Bugs

**Page crashing**
- [ ] The page seems to crash when I try to view the HEAD version's references, but only in this collection. Looking at `/users/jamlung/collections/BA-team-demo/HEAD/references`

**Text wrapping**
- [ ] In constrained views, the reference translation text wraps behind the ref type tag instead of wrapping properly. The translation should wrap below/around the tag.

**Missing definition type tag**
- [ ] Each reference row should have two tags: one for cascade type and one for definition type (intentional vs. extensional).
  - A reference pointing to a specific concept or mapping → **extensional**
  - A reference that gets concepts from a source without specific IDs → **intentional**
  - Cascade is a gray area but intentional/extensional tags should still appear by the same rules

**Pluralization**
- [ ] "1 concepts" should read "1 concept" (singular).

**Resolved repo not displaying**
- [ ] The resolved source/repo+version is not showing on the row at all. Per the mockup, this should appear as our regular on-hover-tooltip button that reveals the resolved repo+version details on hover.

**Expression toggle label is swapped**
- [ ] The raw/translation toggle button shows "raw" when displaying translations, and "translation" when displaying raw. The label should reflect what clicking the button *will switch to*, or it should reflect the current state — either way, it's currently backwards/confusing.
     - We might consider replacing the single toggle button with a segmented/pill control that uses `[ Translation ]  [ Raw ]` 

<img width="218" height="53" alt="Image" src="https://github.com/user-attachments/assets/97829808-1780-4824-9fcf-1ae9d44a5174" />

<img width="1042" height="983" alt="Image" src="https://github.com/user-attachments/assets/7bb20065-9a00-4815-abe9-bd19d1fe56f3" />

**Filter count showing wrong number**
- [ ] The filter count shows `11` when there are 7 references and only 1 filter applied. The source of this `11` is unclear.

**Intentional / extensional filters not working**
- [ ] Even when intentional or extensional references are present, filtering by these types returns no results.

**Cascade filter logic incorrect**
- [ ] The extensional reference for "Include concepts" (which has no cascade) should appear under **Cascade: None**, but it doesn't.
- [ ] "Mappings + target concepts" Cascaded references should appear under **Cascade: Source to Concepts**, but it only shows under **Any**.
- [ ] Intensional/extensional filter is not working correctly.

<img width="1042" height="986" alt="Image" src="https://github.com/user-attachments/assets/f804f583-5c01-444b-a355-169b26fdad38" />




---

### Expansion Dropdown workflow:


- Add a dropdown to select among available expansions for the collection version
- The dropdown should default to the collection version's **default expansion**
- Changing the expansion should realistically update two things only: the **Resolved Repo** column and the **Results** count
- The selected expansion should **persist when switching tabs** (e.g., if you select a non-default expansion on the References tab and then switch to the Concepts tab, the same expansion should remain selected)

---

### Working Correctly ✓
- Cascade tag displaying on rows
- Repository version display (HEAD vs. pinned version)
- Cascade: Any filter
- Cascade: None filter (partially — see bug above)
- Once include filter
- General row format and layout

**Comment by snyaggarwal** [comment]
This is deployed on all env
