### ISSUE TITLE
Revise list of response text, error messages, etc. for oclapi2

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#310]
- [X] Compile a list of all the response text, error messages, etc. in oclapi2 (Sunny)
- [x] Revise list of responses and messages in oclapi2 for clarity and consistency (Maurya)
- [x] 10/07/2020 - Review final list with @paynejd and @harpatel1  
- [x] 10/08/2020 - @maurya to create a consolidated list and send to @snyaggarwal 
- [ ] 10/09/2020  - Review with @snyaggarwal on Architecture call

**Comment by snyaggarwal** [comment]
Most of them I can extract from integration tests.

**Comment by snyaggarwal** [comment]
### Common

- NOT_FOUND = 'Not found.'
- OK_MESSAGE = 'ok!'
- PERSIST_NEW_ERROR_MESSAGE = "An error occurred while trying to persist new {}."
- MUST_SPECIFY_EXTRA_PARAM_IN_BODY = 'Must specify {} param in body.'
- SOURCE_PARENT_CANNOT_BE_NONE = 'Source parent cannot be None.'
- PARENT_RESOURCE_CANNOT_BE_NONE = 'Parent resource cannot be None.'
- CREATOR_CANNOT_BE_NONE = 'Creator cannot be None.'
- CANNOT_DELETE_ONLY_VERSION = 'Cannot delete only version.'
- LOOKUP_ATTRIBUTES_MUST_BE_IMPORTED = 'Lookup attributes must be imported'
 
### Organization

- DELETE_SUCCESS = 'Successfully deleted Organization.'
 
### Sources

- DELETE_FAILURE = 'Could not delete Source.'
- DELETE_SUCCESS = 'Successfully deleted Source.'
- VERSION_ALREADY_EXISTS = 'Source version {} already exist.'

### Collection

- EXPRESSION_INVALID = 'Expression specified is not valid.'
- REFERENCE_ALREADY_EXISTS = 'Concept or Mapping reference name must be unique in a collection.'
- CONCEPT_FULLY_SPECIFIED_NAME_UNIQUE_PER_COLLECTION_AND_LOCALE = "Concept fully specified name must be unique for " \
- "same collection and locale."
- CONCEPT_PREFERRED_NAME_UNIQUE_PER_COLLECTION_AND_LOCALE = "Concept preferred name must be unique for same collection " \
- "and locale."
- HEAD_OF_CONCEPT_ADDED_TO_COLLECTION = 'Added the latest versions of concept to the collection. ' \
- Future updates will not be added automatically.'
- HEAD_OF_MAPPING_ADDED_TO_COLLECTION = 'Added the latest versions of mapping to the collection. ' \
- Future updates will not be added automatically.'
- CONCEPT_ADDED_TO_COLLECTION_FMT = 'The concept {} is successfully added to collection {}'
- MAPPING_ADDED_TO_COLLECTION_FMT = 'The mapping {} is successfully added to collection {}'
- DELETE_FAILURE = 'Could not delete Collection.'
- DELETE_SUCCESS = 'Successfully deleted Collection.'
- NO_MATCH = 'No Collection matches the given query.'
- VERSION_ALREADY_EXISTS = 'Collection version {} already exist.'
-  

### Concept
OPENMRS_ONE_FULLY_SPECIFIED_NAME_PER_LOCALE = 'A concept may not have more than one fully specified name in any locale'
OPENMRS_NO_MORE_THAN_ONE_SHORT_NAME_PER_LOCALE = 'A concept cannot have more than one short name in a locale'
OPENMRS_NAMES_EXCEPT_SHORT_MUST_BE_UNIQUE = 'All names except short names must be unique for a concept and locale'
OPENMRS_FULLY_SPECIFIED_NAME_UNIQUE_PER_SOURCE_LOCALE = 'Concept fully specified name must be unique for ' \
same source and locale'
OPENMRS_MUST_HAVE_EXACTLY_ONE_PREFERRED_NAME = 'A concept may not have more than one preferred name (per locale)'
OPENMRS_SHORT_NAME_CANNOT_BE_PREFERRED = 'A short name cannot be marked as locale preferred'
OPENMRS_AT_LEAST_ONE_FULLY_SPECIFIED_NAME = 'A concept must have at least one fully specified name'
OPENMRS_PREFERRED_NAME_UNIQUE_PER_SOURCE_LOCALE = 'Concept preferred name must be unique for same source and locale'
OPENMRS_DESCRIPTION_LOCALE = 'Invalid description locale'
OPENMRS_NAME_LOCALE = 'Invalid name locale'
OPENMRS_DESCRIPTION_TYPE = 'Invalid description type'
OPENMRS_NAME_TYPE = 'Invalid name type'
OPENMRS_DATATYPE = 'Invalid data type'
OPENMRS_CONCEPT_CLASS = 'Invalid concept class'
BASIC_DESCRIPTION_CANNOT_BE_EMPTY = 'Concept description cannot be empty'
BASIC_NAMES_CANNOT_BE_EMPTY = 'A concept must have at least one name'
CONCEPT_WAS_RETIRED = 'Concept was retired'
CONCEPT_WAS_UNRETIRED = 'Concept was un-retired'
CONCEPT_IS_ALREADY_RETIRED = 'Concept is already retired'
CONCEPT_IS_ALREADY_NOT_RETIRED = 'Concept is already not retired'
ALREADY_EXISTS = "Concept with mnemonic {} already exists for {}"
PERSIST_CLONE_SPECIFY_USER_ERROR = "Must specify which user is attempting to create a new concept version."
PERSIST_CLONE_ERROR = 'An error occurred while saving new concept version.'
COULD_NOT_FIND_CONCEPT_TO_UPDATE = 'Could not find concept to update'
PARENT_VERSION_NOT_LATEST_CANNOT_UPDATE_CONCEPT = 'Parent version is not the latest. Cannot update concept.'
 
### Mapping

- MAPPING_WAS_RETIRED = 'Mapping was retired'
- MAPPING_WAS_UNRETIRED = 'Mapping was un-retired'
- MAPPING_IS_ALREADY_RETIRED = 'Mapping is already retired'
- MAPPING_IS_ALREADY_NOT_RETIRED = 'Mapping is already not retired'
- COULD_NOT_FIND_MAPPING_TO_RETIRE = 'Could not find mapping to retire'
- PERSIST_CLONE_ERROR = 'An error occurred while saving new concept version.'
- COULD_NOT_FIND_MAPPING_TO_UPDATE = 'Could not find mapping to update'
- PARENT_VERSION_NOT_LATEST_CANNOT_UPDATE_MAPPING = 'Parent version is not the latest. Cannot update mapping.'
- PERSIST_CLONE_SPECIFY_USER_ERROR = "Must specify which user is attempting to create a new mapping version."
- OPENMRS_SINGLE_MAPPING_BETWEEN_TWO_CONCEPTS = 'There can be only one mapping between two concepts'
- OPENMRS_INVALID_MAPTYPE = 'Invalid mapping type'
- MUST_SPECIFY_FROM_CONCEPT = "Must specify a 'from_concept'."
- CANNOT_MAP_CONCEPT_TO_SELF = 'Cannot map concept to itself.'
- CANNOT_SPECIFY_BOTH_TO_CONCEPT_OR_TO_SOURCE = "Must specify either 'to_concept' or 'to_source' & 'to_concept_code'."
- MUST_SPECIFY_EITHER_TO_CONCEPT_OR_TO_SOURCE = CANNOT_SPECIFY_BOTH_TO_CONCEPT_OR_TO_SOURCE + " Cannot specify both."
- TO_CONCEPT_UNIQUE_ATTRIBUTES_ERROR_MESSAGE = "Parent, map_type, from_concept, to_concept must be unique."
- TO_SOURCE_UNIQUE_ATTRIBUTES_ERROR_MESSAGE = "Parent, map_type, from_concept, to_source, to_concept_code must be unique."

**Comment by snyaggarwal** [comment]
with this, we should also address responses that don't need any message for example 204.

**Comment by paynejd** [comment]
@maurya Would you be willing to coordinate revising and getting input from others on a revised set of response messages?

@snyaggarwal How would you suggest that we go about reviewing and revising status codes?

**Comment by snyaggarwal** [comment]
@paynejd there is no simpler/automated way to go about it. I would suggest, once the qa2 auth is up and running, we start hitting the APIs and update the response status codes wherever necessary.

**Comment by aprilcurrier** [comment]
Maurya to determine what the goal is. Currently a lack of overall approach. Want to ensure consistency and clarity for non devs.
Maurya to work with Jon.

**Comment by maurya** [comment]
Proposed version -

**Organization**

    DELETE_SUCCESS = "Organization '{}' successfully deleted."
     
**Sources**

    DELETE_FAILURE = "Source '{}' could not be deleted."
    DELETE_SUCCESS = "Source '{}' successfully deleted."
    VERSION_ALREADY_EXISTS = "Source version '{}/{}' already exists." First variable is # sourceId, second variable is  #sourceVersionId

**Comment by maurya** [comment]
Proposed version -
**Collection**

    EXPRESSION_INVALID = "Expression '{}' is not valid."
    REFERENCE_ALREADY_EXISTS = "Concept or mapping reference name '{}' already exists." @snyaggarwal what is a reference name?
    CONCEPT_FULLY_SPECIFIED_NAME_UNIQUE_PER_COLLECTION_AND_LOCALE = "A concept's fully specified name for a locale must be unique in a collection." @snyaggarwal  Where is this error message displayed? https://github.com/OpenConceptLab/oclapi2/blob/c3b8cc04661f5d6c5b491333d0cd22e7508fd2a1/core/collections/models.py#L127. It's not clear from the code. 


**Todo**
    CONCEPT_PREFERRED_NAME_UNIQUE_PER_COLLECTION_AND_LOCALE = "Concept preferred name must be unique for same collection and locale."
    HEAD_OF_CONCEPT_ADDED_TO_COLLECTION = 'Added the latest versions of concept to the collection. Future updates will not be added automatically.'
    HEAD_OF_MAPPING_ADDED_TO_COLLECTION = 'Added the latest versions of mapping to the collection. Future updates will not be added automatically.'
    CONCEPT_ADDED_TO_COLLECTION_FMT = 'The concept {} is successfully added to collection {}'
    MAPPING_ADDED_TO_COLLECTION_FMT = 'The mapping {} is successfully added to collection {}'
    DELETE_FAILURE = 'Could not delete Collection.'
    DELETE_SUCCESS = 'Successfully deleted Collection.'
    NO_MATCH = 'No Collection matches the given query.'
    VERSION_ALREADY_EXISTS = "Collection version '{}' already exist."

**Comment by snyaggarwal** [comment]
@maurya 
`REFERENCE_ALREADY_EXISTS = "Concept or mapping reference name already exists."` -- this is a static message right now. name is not a vairable.
`CONCEPT_FULLY_SPECIFIED_NAME_UNIQUE_PER_COLLECTION_AND_LOCALE` is used while adding expressions (references) in OpenMRS schema type Collections to validate its locales with existing  concepts.

**Comment by maurya** [comment]
To Review with @paynejd and @harpatel1  - 
**Collection** 

REFERENCE_ALREADY_EXISTS = "Concept or mapping reference name '{}' already exists."
_CONCEPT_FULLY_SPECIFIED_NAME_UNIQUE_PER_COLLECTION_AND_LOCALE = "Concept fully specified name '{}' must be unique in a collection for the same locale."
CONCEPT_PREFERRED_NAME_UNIQUE_PER_COLLECTION_AND_LOCALE = "Concept preferred name '{}' must be unique in a collection for the same locale."
HEAD_OF_CONCEPT_ADDED_TO_COLLECTION = "Version '{}' of concept '{}' added to the collection. Future updates will not be added automatically."
HEAD_OF_MAPPING_ADDED_TO_COLLECTION = "Version '{}' of mapping '{}' added to the collection. Future updates will not be added automatically."_
CONCEPT_ADDED_TO_COLLECTION_FMT = "Concept '{}' is successfully added to collection '{}'."
MAPPING_ADDED_TO_COLLECTION_FMT = "Mapping '{}' is successfully added to collection '{}'."
DELETE_FAILURE = "Collection '{}' could not be deleted."
DELETE_SUCCESS ="Collection '{}' successfully deleted."
NO_MATCH = "Query '{}' does not match any collection."
VERSION_ALREADY_EXISTS = "Collection '{}' version '{}' already exists."

**Comment by maurya** [comment]
**Concept**

    OPENMRS_ONE_FULLY_SPECIFIED_NAME_PER_LOCALE = "Concept '{}' cannot have more than one fully specified name in a locale."
    OPENMRS_NO_MORE_THAN_ONE_SHORT_NAME_PER_LOCALE = "Concept '{}' cannot have more than one short name in a locale."
    OPENMRS_NAMES_EXCEPT_SHORT_MUST_BE_UNIQUE = "All names except short names must be unique for a concept and locale."
    OPENMRS_FULLY_SPECIFIED_NAME_UNIQUE_PER_SOURCE_LOCALE = "Concept fully specified name '{}' must be unique for the same source and locale."
    OPENMRS_MUST_HAVE_EXACTLY_ONE_PREFERRED_NAME = "Concept '{}' cannot have more than one preferred name in the same locale'
    OPENMRS_SHORT_NAME_CANNOT_BE_PREFERRED = "Short name cannot be marked as locale preferred."
    OPENMRS_AT_LEAST_ONE_FULLY_SPECIFIED_NAME = "Concept '{}' must have at least one fully specified name."
    OPENMRS_PREFERRED_NAME_UNIQUE_PER_SOURCE_LOCALE = "Concept preferred name '{}' must be unique for same source and locale"
OPENMRS_DESCRIPTION_LOCALE = "Invalid description locale"
OPENMRS_NAME_LOCALE = 'Invalid name locale'
OPENMRS_DESCRIPTION_TYPE = 'Invalid description type'
OPENMRS_NAME_TYPE = 'Invalid name type'
OPENMRS_DATATYPE = 'Invalid data type'
OPENMRS_CONCEPT_CLASS = 'Invalid concept class'
    BASIC_DESCRIPTION_CANNOT_BE_EMPTY = "Concept description cannot be empty."
BASIC_NAMES_CANNOT_BE_EMPTY = "Concept must have at least one fully specified name."
    CONCEPT_WAS_RETIRED = "Concept '{}' was retired."
    CONCEPT_WAS_UNRETIRED = "Concept '{}' was un-retired"
    CONCEPT_IS_ALREADY_RETIRED = "Concept '{}' is already retired."
    CONCEPT_IS_ALREADY_NOT_RETIRED = "Concept '{}' is already not retired."
ALREADY_EXISTS = "Concept with mnemonic {} already exists for {}" --> "Concept ID must be unique within a source."
PERSIST_CLONE_SPECIFY_USER_ERROR = "Must specify which user is attempting to create a new concept version '{}'."
PERSIST_CLONE_ERROR = "An error occurred while saving the new concept version '{}'."
    COULD_NOT_FIND_CONCEPT_TO_UPDATE = "Concept '{}' to update not found."
PARENT_VERSION_NOT_LATEST_CANNOT_UPDATE_CONCEPT = "Concept '{}' cannot be updated. Parent version '{}' is not the latest. Please update to latest version '{}'."

**Comment by aprilcurrier** [comment]
50% complete upon rollover. Reviewing messages and will work with Sunny once all are reviewed.

**Comment by maurya** [comment]
Mapping

    MAPPING_WAS_RETIRED = "Mapping '{}' was retired."
    MAPPING_WAS_UNRETIRED = "Mapping '{}' was un-retired."
    MAPPING_IS_ALREADY_RETIRED = "Mapping '{}' is already retired."
    MAPPING_IS_ALREADY_NOT_RETIRED = "Mapping '{}' is already un-retired."
    COULD_NOT_FIND_MAPPING_TO_RETIRE = "Mapping '{}' to retire not found."
    PERSIST_CLONE_ERROR = "An error occurred while saving the new concept version '{}'." - 1. Common message. 2. Can this be more descriptive.
    COULD_NOT_FIND_MAPPING_TO_UPDATE = "Mapping '{}' to update not found."
    PARENT_VERSION_NOT_LATEST_CANNOT_UPDATE_MAPPING = "Mapping '{}' cannot be updated. Parent version '{}' is not the latest. Please update the parent to the latest version '{}'."
    PERSIST_CLONE_SPECIFY_USER_ERROR = "Must specify which user is attempting to create a new mapping version."
    OPENMRS_SINGLE_MAPPING_BETWEEN_TWO_CONCEPTS = 'There can be only one mapping between two concepts'
    OPENMRS_INVALID_MAPTYPE = 'Invalid mapping type'
    MUST_SPECIFY_FROM_CONCEPT = "Must specify a 'from_concept'."
    CANNOT_MAP_CONCEPT_TO_SELF = 'Cannot map concept to itself.'
    CANNOT_SPECIFY_BOTH_TO_CONCEPT_OR_TO_SOURCE = "Must specify either 'to_concept' or 'to_source' & 'to_concept_code'."
    MUST_SPECIFY_EITHER_TO_CONCEPT_OR_TO_SOURCE = CANNOT_SPECIFY_BOTH_TO_CONCEPT_OR_TO_SOURCE + " Cannot specify both."
    TO_CONCEPT_UNIQUE_ATTRIBUTES_ERROR_MESSAGE = "Parent, map_type, from_concept, to_concept must be unique."
    TO_SOURCE_UNIQUE_ATTRIBUTES_ERROR_MESSAGE = "Parent, map_type, from_concept, to_source, to_concept_code must be unique."

**Comment by maurya** [comment]
Common -

    NOT_FOUND = "Not found."
    OK_MESSAGE = 'Okay.'
    PERSIST_NEW_ERROR_MESSAGE = "An error occurred while trying to persist new {}." - Can we include more detail on the error?
    MUST_SPECIFY_EXTRA_PARAM_IN_BODY = "Must specify '{}' param in body."
    SOURCE_PARENT_CANNOT_BE_NONE = "Source parent cannot be None."
    PARENT_RESOURCE_CANNOT_BE_NONE = "Parent resource cannot be None."
    CREATOR_CANNOT_BE_NONE = "Creator cannot be None."
    CANNOT_DELETE_ONLY_VERSION = "Version '{}' is the only version for this element. Cannot delete only version."
    LOOKUP_ATTRIBUTES_MUST_BE_IMPORTED = "Lookup attributes must be imported."

**Comment by maurya** [comment]
**Consolidated list -**

- All messages start and end with double quotes.  
- All messages end with a period.
- Preference to show more detail instead of generic message. Version number, Concept Id and so on.
- Preference to show more detail for an error instead of generic "Error occured." message

**Comment by aprilcurrier** [comment]
@snyaggarwal  to review prior to Arch call Friday  the 23rd

**Comment by maurya** [comment]
@snyaggarwal any update on this?

**Comment by snyaggarwal** [comment]
Below are the replies:

Collection -
Questions -

REFERENCE_ALREADY_EXISTS - What is a reference name ? Where is it used? -- This is thrown when a concept/mapping URL (reference) is added to collection and it already exists in the collection.
DELETE_FAILURE - Can we provide causes for failure ? to make it more clear -- when we try to delete a collection and it fails the primary response is the exception message which is actual reason(s) for failure, if an unknown exception is raised only then this DELETE_FAILURE is returned.

Mapping -
Questions -

PERSIST_CLONE_ERROR - a.should this be a common message? b.can this be more descriptive? c. can we add an exception message here? -- this is a fail-safe step. We try to throw an actual exception message but if we somehow miss it then as a fail-safe this is returned.
PARENT_VERSION_NOT_LATEST_CANNOT_UPDATE_MAPPING - a. Is this even relevant in the new postgres model. ? b. When is this produced? Also use source or collection version instead of parent. --- you are right! this is not relevant. Removed this.
PERSIST_CLONE_SPECIFY_USER_ERROR - a. Can this be just authentication error as the user is already signed in to reach this point? -- well you are right. This is again a fail-safe in the method if user arg is not provided whiling creating version we return this error. I suggest we keep it as it is.
MUST_SPECIFY_EITHER_TO_CONCEPT_OR_TO_SOURCE - a. Should this be for a case when neither is specified ? if yes message - "At least 'to_concept' or 'to_source' & 'to_concept_code' must be provided." -- This is the case when when internal to concept URL is provided with to_concept_code.


Common -
Questions -

NOT_FOUND - Return 404 Not Found and No message or Lets give some context on what event occurred. -- No message is better. Will change it.
OK_MESSAGE - Return 200 OK and No message or Lets give some context on what event occurred. -- No message is better. Will change it.
PERSIST_NEW_ERROR_MESSAGE - Can we include more detail on the error? -- this is a fail-safe step. We try to throw an actual exception message but if we somehow miss it then as a fail-safe this is returned.
SOURCE_PARENT_CANNOT_BE_NONE - When is this the case? -- this is same as PARENT_RESOURCE_CANNOT_BE_NONE. its when you try to POST source/collection without specifying parent.
PARENT_RESOURCE_CANNOT_BE_NONE - When is this the case?  -- this is same as SOURCE_PARENT_CANNOT_BE_NONE. its when you try to POST source/collection without specifying parent.
CREATOR_CANNOT_BE_NONE - When is this the case? -- this will never happen as it is managed by perms. Removing this.
LOOKUP_ATTRIBUTES_MUST_BE_IMPORTED - Can we provide which lookup attributes or a link for absolute url for a bigger list. -- this is unused and not valid for oclapi2. This was raised in v1 while validating mapping when-if lookup values are not imported. In v2 that will never happen as we load lookup values as seed data (fixtures) while booting up the application.

**Comment by aprilcurrier** [comment]
@paynejd  and @maurya  to discuss at a check-in

**Comment by maurya** [comment]
I've added quotes to the messages still to be reviewed.

**Comment by maurya** [comment]
Updated messages -

Collection -
REFERENCE_ALREADY_EXISTS = "Concept or mapping reference '{}' already exists."
DELETE_FAILURE = "Source '{}' could not be deleted due to a server error."

Mappings (**To be updated when we update mapping behavior.**) -
PERSIST_CLONE_ERROR = "Could not create concept version '{}' due to a server error."  #conceptVersionId
PERSIST_CLONE_SPECIFY_USER_ERROR = "Must specify which user is attempting to create a new mapping version."

Common -
PERSIST_NEW_ERROR_MESSAGE = "'{}' could not be saved due to a system error."
SOURCE_PARENT_CANNOT_BE_NONE = "A new source must have a user or an organization owner ." 
@snyaggarwal is SOURCE_PARENT_CANNOT_BE_NONE and PARENT_RESOURCE_CANNOT_BE_NONE the same use case, you response above indicates they are the same.

**Comment by maurya** [comment]
To be reviewed by @snyaggarwal

**Comment by aprilcurrier** [comment]
@snyaggarwal  any update here?

**Comment by snyaggarwal** [comment]
Haven't implemented this yet, moving in sprint backlog.

**Comment by aprilcurrier** [comment]
@snyaggarwal  to implement as time permits
