### ISSUE TITLE
FISMA

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#664]
_Copied from DATIM-OCL repo, owned by PEPFAR_
# Predecessor is #760 

Include information around:

 - Deployment procedure
 - Content Update (e.g. PDH)

# Documents

- [ ] ISPC Plan
 Need to Document release process as part of ISCP documentation as well
Need to include  information on - Data Corruption Risk Mitigation Plan Iin the ISCP plan 

#### 9/18/20

> -  working towards migration of AWS
> - Rafal is investigating the process 
> - Different tooling options 
> - CINTIA manages infrastructure for OpenMRS
> - Will present findings on next Friday Arch call
> - Expects to have some infa. up by  Oct 

- [x] iMatrix Questions
- [x] Equipment Application List 
- [x] Ports Protocols and Services
- [x] System Connections
- [x] Software Application List 
- [x] MSP OCL e-authentication form (received 9/29/20)

#### 12/3/20 FISMA Next Steps 

- [ ] - BAO process - Ailcia 
- [ ] - Hatem boundary diagram - receive by Dec 10 
- [ ] - Hatem process and test requirements receive by Dec 10 
- [ ] - establish requirements with the contact of IRM official designated - WHO? 
- [ ] - Fill out system catergorization form  https://docs.google.com/spreadsheets/d/17d7J-SBY7XwD0bGmhQO9W119xHtupRDi/edit#gid=570389155 

# Folder with all of the FISMA assessment documentation thus far:  
## https://drive.google.com/drive/folders/13QCF6R3UTo8tBvoqTJwNzMH0RLdQs7rE 

Include information around 

- [ ] - Deployment procedure
- [ ] - Content Update (e.g. PDH)

Received an initial categorization of low risk. Working on additional documentation: iMatrix questions week on 9/14
