### ISSUE TITLE
Enable FHIR UI as a Feature Toggle 

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#756]
Currently, only ocladmin account can view other servers, including the FHIR UI, in OCL TermBrowser. Let's make it so that we can enable selected other users to use this feature too. Ideally, admin users should be able to enable/disable the server switching feature for other users.

This will enable testing and feedback of the FHIR UI by other accounts.

May need to discuss implementation in the future i.e. who can give access (just ocladmin or any administrative user) and what FHIR servers a user can access. For now, it should probably be an "all-or-nothing" sort of access though.

**Comment by snyaggarwal** [comment]
@jamlung-ri @paynejd

### Tasks:
- [x] Django user groups for `ocl_servers`, `ocl_fhir_servers`, `hapi_fhir_servers`
- [x] API to GET user with assigned `server_groups` -- `GET /users/foobar/?includeServerGroups=true`
- [x] API to PUT user with updated `server_groups`
- [x] Any user with admin privileges or one of the three server_groups assigned can see the "switch server" option
- [x] Any admin should be able to add/remove server_groups from a user using the "Edit Profile" option for that user on user home `/#/users/:username/`
- [x] Server list for a user should be populated using user_groups assigned.

**Comment by jamlung-ri** [comment]
@snyaggarwal I was able to perform the operations you listed above, and it seems to be working well. One issue I am having, however, is when the UI takes me to the last environment I was in before closing the browser tab. I'll go to https://app.qa.openconceptlab.org/ , and it takes me to the HAPI FHIR server, where I cannot get back to the OCL QA environment. The server-switching mechanism is blank (see image below). 

![image](https://user-images.githubusercontent.com/55999682/118485771-d065d500-b6e6-11eb-9464-afb3b1d70a3d.png)

Any thoughts on this? I wonder if it'd be easiest to not save the last environment the user was in, and just send the user to the QA environment by default when navigating to https://app.qa.openconceptlab.org/

**Comment by snyaggarwal** [comment]
@jamlung-ri this should not have happened! It was supposed to handle this.
I tried closing the tab and reopening it, and it worked fine for me.
Can you please describe steps to reproduce this?

**Comment by jamlung-ri** [comment]
I think that the last page I had visited was the HAPI FHIR page, so it might have just left me there but logged off my account. However, now that you checked in the safe guard, it works well, and I was able to get back to OCL QA and then log in. Now I can switch back and forth between servers seamlessly.

**Comment by jamlung-ri** [comment]
We discussed this on the OCL Dev call today, and everything is looking good!
